from fpdf import FPDF


class PDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', '', 8)
        self.cell(0, 10, 'Page %s (Autogenerated by Invoicerr)' % self.page_no(), 0, 0, 'C')


class Invoice:

    def __init__(self, invoice_details: dict):
        self.invoice_details = invoice_details

        self.pdf = PDF(orientation='P', unit='pt', format='A5')
        self.pdf.alias_nb_pages()

        self.pdf.set_margins(left=20, top=50, right=20)
        self.pdf.add_page()

    def __make_head(self):
        self.pdf.set_font('Arial', '', 14)
        self.pdf.cell(0, 14, f"Invoice #{self.invoice_details['invoice_no']}", 0, 1)

        self.pdf.set_font('Arial', 'B', 16)
        self.pdf.cell(0, 24, f"{self.invoice_details['shop']['name']}", 0, 1)

        self.pdf.set_font('Arial', '', 10)
        self.pdf.set_text_color(108, 108, 108)
        self.pdf.multi_cell(140, 12, f"{self.invoice_details['shop']['address']}")
        self.pdf.multi_cell(140, 12, f"{self.invoice_details['shop']['website']}")

    def __make_customer_details(self):
        self.pdf.set_text_color(0)

        self.pdf.multi_cell(0, 28, "", 0, 'L')

        self.pdf.set_font('Arial', 'B', 10)
        self.pdf.multi_cell(0, 0, "Billed to,", 0, 'L')
        self.pdf.multi_cell(0, 0, "Subtotal", 0, 'R')

        self.pdf.multi_cell(0, 14, "", 0, 'L')

        self.pdf.set_font('Arial', '', 10)
        self.pdf.set_text_color(108, 108, 108)
        self.pdf.multi_cell(0, 0, f"{self.invoice_details['customer_name']}", 0, 'L')
        self.pdf.multi_cell(0, 0, f"Rs. {self.invoice_details['subtotal']}", 0, 'R')
        self.pdf.multi_cell(0, 24, f"{self.invoice_details['customer_email']}", 0, 'L')
        self.pdf.multi_cell(0, 0, f"{self.invoice_details['customer_phone']}", 0, 'L')

    def __make_invoice_table(self):
        self.pdf.multi_cell(0, 6, '')

        self.pdf.multi_cell(0, 16, '')
        self.pdf.multi_cell(0, 0, '', 1, 1)
        self.pdf.multi_cell(0, 16, '')

        self.pdf.set_font('Arial', 'B', 10)
        self.pdf.set_text_color(0)

        self.pdf.multi_cell(200, 0, 'Item')
        self.pdf.set_x(200)
        self.pdf.multi_cell(60, 0, 'Qty')
        self.pdf.set_x(260)
        self.pdf.multi_cell(60, 0, 'Amt')
        self.pdf.set_x(320)
        self.pdf.multi_cell(60, 0, 'Cost')
        self.pdf.set_x(380)
        self.pdf.multi_cell(60, 0, 'Tax')

        self.pdf.multi_cell(0, 16, '')
        self.pdf.multi_cell(0, 0, '', 1, 1)
        self.pdf.multi_cell(0, 16, '')

        self.pdf.set_x(20)

        self.pdf.set_font('Arial', '', 10)
        self.pdf.set_text_color(108, 108, 108)

        for i in self.invoice_details['po_items']:
            m_y = self.pdf.get_y()

            self.pdf.multi_cell(170, 10, i['product_name'])
            self.pdf.set_y(m_y)

            self.pdf.set_x(200)
            self.pdf.multi_cell(60, 10, str(i['quantity']))
            self.pdf.set_y(m_y)

            self.pdf.set_x(260)
            self.pdf.multi_cell(60, 10, f'Rs. {i["amount"]}')
            self.pdf.set_y(m_y)

            self.pdf.set_x(320)
            self.pdf.multi_cell(60, 10, f'Rs. {i["cost"]}')
            self.pdf.set_y(m_y)

            self.pdf.set_x(380)
            self.pdf.multi_cell(60, 10, str(i['tax']) + "%")

            self.pdf.set_x(20)
            self.pdf.multi_cell(0, 34, '')

        self.pdf.set_text_color(0)
        self.pdf.multi_cell(0, 0, '', 1, 1)
        self.pdf.multi_cell(0, 8, '')
        self.pdf.multi_cell(0, 16,
                            f"Tax : {str(self.invoice_details['tax'])}%\n"
                            f"Discount : {str(self.invoice_details['discount'])}%\n"
                            f"Subtotal : Rs. {str(self.invoice_details['subtotal'])}",
                            0, 'L')
        self.pdf.multi_cell(0, 8, '')
        self.pdf.multi_cell(0, 0, '', 1, 1)

        self.pdf.set_creator('Invoicerr Auto Invoice')

    def get_output(self, file_name: str):
        self.__make_head()
        self.__make_customer_details()
        self.__make_invoice_table()

        self.pdf.output(f'./invoices/{file_name}.pdf')
