from fpdf import FPDF
import datetime


class PDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', '', 8)
        self.cell(0, 10, 'Page %s (Autogenerated by Invoicerr)' %
                  self.page_no(), 0, 0, 'C')


class Invoice:

    def __init__(self, invoice_details: dict):
        self.invoice_details = invoice_details

        self.pdf = PDF(format='A4', unit='pt', orientation='P')
        self.pdf.add_page()
        self.pdf.set_margins(40, 60, 40)

    def __make_head(self):
        top = self.pdf.get_y()

        # Write Company Name
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.set_font('Arial', 'B', 18)
        self.pdf.multi_cell(txt='{}'.format(self.invoice_details['shop']['name']).upper(), h=20, w=200)

        # Write Company Name and Phone.
        self.pdf.set_y(top)
        self.pdf.set_x(320)
        self.pdf.set_font('Arial', '', 10)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.multi_cell(txt='{} ({})'.format(self.invoice_details['shop']['contact_person_name'],
                                                 self.invoice_details['shop']['contact_person_designation']),
                            h=12, w=110, align='R')
        self.pdf.set_x(320)
        self.pdf.multi_cell(txt='{}'.upper().format(self.invoice_details['shop']['contact_person_phone']), h=12, w=110,
                            align='R')

        # Write Company Address.
        self.pdf.set_margins(40, 60, 40)
        self.pdf.set_y(top)
        self.pdf.set_x(320 + 110 + 20)
        self.pdf.set_font('Arial', '', 10)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.multi_cell(
            txt='{}\n{}'.format(self.invoice_details['shop']['address'], self.invoice_details['shop']['website']), h=12,
            w=110, align='R')
        self.pdf.multi_cell(h=70, w=0)

    def __make_customer_details(self):
        # Write Invoice Info..
        info_height = []
        top = self.pdf.get_y()
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt='Billed To,', h=12, w=110)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.multi_cell(
            txt='{}\n{}\n{}'.format(self.invoice_details['customer_name'], self.invoice_details['customer_address'],
                                    self.invoice_details['customer_phone']),
            h=12,
            w=110)
        info_height.append(self.pdf.get_y())

        self.pdf.set_y(top)
        self.pdf.set_x(200)
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt='Date of Issue', h=12, w=110)
        self.pdf.set_text_color(0, 0, 0)

        self.pdf.set_x(200)
        self.pdf.multi_cell(txt='{}'.format(
            datetime.datetime.strptime(self.invoice_details['created_at'].split('T')[0], '%Y-%m-%d').strftime(
                "%d/%m/%Y")), h=12, w=110)

        self.pdf.multi_cell(h=10, w=0)

        self.pdf.set_x(200)
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt='Due Date', h=12, w=110)
        self.pdf.set_text_color(0, 0, 0)

        self.pdf.set_x(200)
        if self.invoice_details['due_date'] is not None:
            self.pdf.multi_cell(
                txt='{}'.format(
                    datetime.datetime.strptime(self.invoice_details['created_at'].split('T')[0], '%Y-%m-%d').strftime(
                        "%d/%m/%Y")), h=12,
                w=110)
        else:
            self.pdf.multi_cell(txt='N/A', h=12, w=110)

        info_height.append(self.pdf.get_y())

        self.pdf.set_y(top)
        self.pdf.set_x(310)
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt='Invoice No.', h=12, w=110)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_x(310)
        self.pdf.multi_cell(txt='{}'.format(self.invoice_details['invoice_no']), h=12, w=110)

        self.pdf.multi_cell(h=10, w=0)

        self.pdf.set_text_color(18, 96, 171)
        self.pdf.set_x(310)
        self.pdf.multi_cell(txt='Reference No.', h=12, w=110)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_x(310)
        self.pdf.multi_cell(txt='N/A', h=12, w=110)
        info_height.append(self.pdf.get_y())

        self.pdf.set_y(top)
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt='Amount Due (INR)', h=12, w=0, align='R')
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_font(size=18, family='Arial', style='B')
        self.pdf.multi_cell(txt='{}/-'.format(self.invoice_details['pending_amount']), h=22, w=0, align='R')

        self.pdf.multi_cell(h=10, w=0)
        self.pdf.set_font('Arial', '', 10)

        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt='Subtotal (INR)', h=12, w=0, align='R')
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_font(size=18, family='Arial', style='B')
        self.pdf.multi_cell(txt='{}/-'.format(self.invoice_details['subtotal']), h=22, w=0, align='R')
        info_height.append(self.pdf.get_y())

        self.pdf.set_y(max(info_height))
        self.pdf.multi_cell(h=18, w=0)

    def __make_invoice_table(self):
        self.pdf.set_fill_color(18, 96, 171)
        self.pdf.multi_cell(h=1.6, w=0, fill=1)
        self.pdf.multi_cell(h=2, w=0)

        # Write table head
        self.pdf.set_font('Arial', '', 10)
        self.pdf.set_text_color(18, 96, 171)
        top = self.pdf.get_y()
        self.pdf.multi_cell(txt='Description', w=300, h=22)

        self.pdf.set_y(top)
        self.pdf.set_x(360)
        self.pdf.multi_cell(txt='Rate', w=60, h=22)

        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 10)
        self.pdf.multi_cell(txt='Qty', w=60, h=22)

        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 60 + 10)
        self.pdf.multi_cell(txt='Line Total', w=60, h=22)

        self.pdf.multi_cell(w=00, h=6)

        self.pdf.set_text_color(0, 0, 0)

        # Write entries in loop
        for itm in self.invoice_details['po_items']:
            if self.pdf.get_y() > 720:
                self.pdf.add_page('P')

            max_cal_help_arr = []
            top = self.pdf.get_y()
            self.pdf.multi_cell(txt='{}'.format(itm['product_name']), h=12, w=300)
            self.pdf.set_text_color(72, 83, 101)
            self.pdf.multi_cell(txt="{}".format(itm['serial_no']), w=300, h=14)
            self.pdf.set_text_color(0, 0, 0)
            max_cal_help_arr.append(self.pdf.get_y())

            self.pdf.set_y(top)
            self.pdf.set_x(360)
            self.pdf.multi_cell(txt="Rs." + str(itm['cost']) + "/-", w=60, h=12)
            self.pdf.set_x(360)
            self.pdf.set_text_color(72, 83, 101)
            self.pdf.multi_cell(txt="+{}% Tax".format(itm['tax']), w=300, h=14)
            self.pdf.set_text_color(0, 0, 0)
            max_cal_help_arr.append(self.pdf.get_y())

            self.pdf.set_y(top)
            self.pdf.set_x(360 + 60 + 10)
            self.pdf.multi_cell(txt=str(itm['quantity']), w=60, h=12)
            max_cal_help_arr.append(self.pdf.get_y())

            self.pdf.set_y(top)
            self.pdf.set_x(360 + 60 + 60 + 10)
            self.pdf.multi_cell(txt="Rs. " + str(itm['amount']) + "/-", w=60, h=12)
            max_cal_help_arr.append(self.pdf.get_y())

            self.pdf.set_y(max(max_cal_help_arr))
            self.pdf.multi_cell(h=6, w=0)
            self.pdf.set_fill_color(203, 213, 224)
            self.pdf.multi_cell(h=0.2, w=0, fill=1)
            self.pdf.multi_cell(h=8, w=0)

        self.pdf.multi_cell(h=28, w=0)

        self.pdf.set_creator('Invoicerr Auto Invoice')

    def __write_footer_info(self):
        # Write Footer Information.
        top = self.pdf.get_y()
        self.pdf.set_x(360)
        self.pdf.multi_cell(txt="Subtotal", w=60, h=12)
        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 60)
        self.pdf.multi_cell(txt="Rs. {}/-".format(self.invoice_details['subtotal']), w=0, h=12, align='R')

        self.pdf.multi_cell(w=0, h=2)

        top = self.pdf.get_y()
        self.pdf.set_x(360)
        self.pdf.multi_cell(txt="Discount", w=60, h=12)
        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 60)
        self.pdf.multi_cell(txt="- Rs. {}/-".format(self.invoice_details['discount']), w=0, h=12, align='R')

        self.pdf.multi_cell(w=0, h=2)

        top = self.pdf.get_y()
        self.pdf.set_x(360)
        self.pdf.multi_cell(txt="Tax / GST", w=60, h=12)
        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 60)
        self.pdf.multi_cell(txt="Rs. {PENDING}/-", w=0, h=12, align='R')

        self.pdf.multi_cell(w=0, h=6)

        self.pdf.set_x(595.35 / 2)
        self.pdf.multi_cell(h=0, w=0, fill=1, align='R')

        self.pdf.multi_cell(w=0, h=6)

        top = self.pdf.get_y()
        self.pdf.set_x(360)
        self.pdf.set_text_color(18, 96, 171)
        self.pdf.multi_cell(txt="Grand Total", w=60, h=12)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 60)
        self.pdf.multi_cell(txt="Rs. {}/-".format(self.invoice_details['subtotal'] - self.invoice_details['discount']),
                            w=0, h=12, align='R')

        top = self.pdf.get_y()
        self.pdf.set_x(360)
        self.pdf.set_text_color(229, 62, 62)
        self.pdf.multi_cell(txt="Pending", w=60, h=12)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_y(top)
        self.pdf.set_x(360 + 60 + 60)
        self.pdf.multi_cell(txt="Rs. {}/-".format(self.invoice_details['pending_amount']), w=0, h=12, align='R')

        self.pdf.multi_cell(h=6, w=0)
        self.pdf.set_x(595.35 / 2)
        self.pdf.multi_cell(h=0, w=0, fill=1, align='R')
        self.pdf.multi_cell(h=6, w=0)

    def get_output(self, file_name: str):
        self.__make_head()
        self.__make_customer_details()
        self.__make_invoice_table()
        self.__write_footer_info()

        self.pdf.output(f'./invoices/{file_name}.pdf')
