# Generated by Django 4.0.1 on 2022-01-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
    ]
