# Generated by Django 4.0.1 on 2022-01-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0004_alter_customuser_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
    ]
