# Generated by Django 4.0.1 on 2022-01-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_verified',
        ),
    ]
