# Generated by Django 4.0.4 on 2022-04-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=40, null=True)),
                ('customer_email', models.CharField(default=None, max_length=40, null=True)),
                ('customer_address', models.CharField(default=None, max_length=100, null=True)),
                ('customer_phone', models.CharField(default=None, max_length=40, null=True)),
                ('subtotal', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('invoice_no', models.BigIntegerField()),
                ('pending_amount', models.FloatField(default=0.0)),
                ('due_date', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('serial_no', models.CharField(default='', max_length=30)),
                ('cost', models.FloatField()),
                ('tax', models.FloatField()),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.purchaseorder')),
            ],
        ),
    ]
