# Generated by Django 4.0.1 on 2022-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
