# Generated by Django 4.0.1 on 2022-01-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_purchaseorder_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='product_name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
