# Generated by Django 4.0.1 on 2022-01-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_alter_purchaseorder_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='product_name',
        ),
    ]
