# Generated by Django 4.0.1 on 2022-01-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_remove_poitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
