# Generated by Django 4.0.1 on 2022-01-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0007_poitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='product',
        ),
    ]
