# Generated by Django 4.0.1 on 2022-01-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_logo'),
        ('purchase_orders', '0008_remove_poitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
