# Generated by Django 4.0.1 on 2022-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0010_remove_purchaseorder_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_email',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_phone',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
