# Generated by Django 4.0.3 on 2022-04-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0011_purchaseorder_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pending_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
