# Generated by Django 4.0.3 on 2022-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0012_purchaseorder_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax',
        ),
    ]
