# Generated by Django 4.0.3 on 2022-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0013_remove_poitem_discount_remove_purchaseorder_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
