# Generated by Django 4.0.3 on 2022-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0014_purchaseorder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
