# Generated by Django 4.0.3 on 2022-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0015_purchaseorder_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='serial_no',
            field=models.CharField(default='', max_length=30),
        ),
    ]
