# Generated by Django 4.0.4 on 2022-04-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('website', models.CharField(blank=True, max_length=70, null=True)),
                ('address', models.TextField(max_length=200)),
                ('contact_person_name', models.CharField(default='', max_length=25)),
                ('contact_person_designation', models.CharField(default='', max_length=25)),
                ('contact_person_phone', models.CharField(default='', max_length=13)),
                ('gstin_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
                ('available_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
