# Generated by Django 4.0.3 on 2022-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_person_designation',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_person_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_person_phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
